package com.laptrinhtichhop.moigioinhatro.entities;
// Generated Dec 9, 2020, 8:44:57 PM by Hibernate Tools 5.4.21.Final

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Anh generated by hbm2java
 */
@Entity
@Table(name = "ANH")
@XmlRootElement
public class Anh implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ma_anh")
	private Integer maAnh;

	@JoinColumn(name = "ma_phieu_dang")
	@ManyToOne
	private PhieuDangPhong phieuDangPhong;

	@Column(name = "duong_dan")
	private String duongDan;

	public Anh() {
	}

	public Anh(String duongDan) {
		this.duongDan = duongDan;
	}

	public Anh(PhieuDangPhong phieuDangPhong, String duongDan) {
		this.phieuDangPhong = phieuDangPhong;
		this.duongDan = duongDan;
	}

	public Integer getMaAnh() {
		return this.maAnh;
	}

	public void setMaAnh(Integer maAnh) {
		this.maAnh = maAnh;
	}

	public PhieuDangPhong getPhieuDangPhong() {
		return this.phieuDangPhong;
	}

	public void setPhieuDangPhong(PhieuDangPhong phieuDangPhong) {
		this.phieuDangPhong = phieuDangPhong;
	}

	public String getDuongDan() {
		return this.duongDan;
	}

	public void setDuongDan(String duongDan) {
		this.duongDan = duongDan;
	}

}
