package com.laptrinhtichhop.moigioinhatro.entities;
// Generated Dec 9, 2020, 8:44:57 PM by Hibernate Tools 5.4.21.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ChuPhong generated by hbm2java
 */
@Entity
@Table(name = "CHU_PHONG")
@XmlRootElement
public class ChuPhong implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "so_CMND")
	private String soCmnd;
	
	@Column(name = "ho_ten")
	private String hoTen;

	@Column(name = "so_dien_thoai")
	private String soDienThoai;

	@Column(name = "dia_chi")
	private String diaChi;

	@Column(name = "gioi_tinh")
	private boolean gioiTinh;

	@Column(name = "ngay_sinh")
	private Date ngaySinh;

	@Column(name = "ten_dang_nhap")
	private String tenDangNhap;

	@Transient
	@OneToMany(mappedBy="maPhieuDang")
	private Set<PhieuDangPhong> phieuDangPhongs = new HashSet<PhieuDangPhong>(0);

	public ChuPhong() {
	}

	public ChuPhong(String soCmnd, String hoTen, String soDienThoai, String diaChi, boolean gioiTinh,
			String tenDangNhap) {
		this.soCmnd = soCmnd;
		this.hoTen = hoTen;
		this.soDienThoai = soDienThoai;
		this.diaChi = diaChi;
		this.gioiTinh = gioiTinh;
		this.tenDangNhap = tenDangNhap;
	}

	public ChuPhong(String soCmnd, String hoTen, String soDienThoai, String diaChi, boolean gioiTinh,
			Date ngaySinh, String tenDangNhap, Set<PhieuDangPhong> phieuDangPhongs) {
		this.soCmnd = soCmnd;
		this.hoTen = hoTen;
		this.soDienThoai = soDienThoai;
		this.diaChi = diaChi;
		this.gioiTinh = gioiTinh;
		this.ngaySinh = ngaySinh;
		this.tenDangNhap = tenDangNhap;
		this.phieuDangPhongs = phieuDangPhongs;
	}

	public String getSoCmnd() {
		return this.soCmnd;
	}

	public void setSoCmnd(String soCmnd) {
		this.soCmnd = soCmnd;
	}

	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public boolean isGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	public Set<PhieuDangPhong> getPhieuDangPhongs() {
		return this.phieuDangPhongs;
	}

	public void setPhieuDangPhongs(Set<PhieuDangPhong> phieuDangPhongs) {
		this.phieuDangPhongs = phieuDangPhongs;
	}

}
