package com.laptrinhtichhop.moigioinhatro.entities;
// Generated Dec 9, 2020, 8:44:57 PM by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * LoaiPhong generated by hbm2java
 */
@Entity
@Table(name = "LOAI_PHONG")
@XmlRootElement
public class LoaiPhong implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ma_loai_phong")
	private Integer maLoaiPhong;

	@Column(name = "ten_loai_phong")
	private String tenLoaiPhong;
	
	@Transient
	@OneToMany(mappedBy = "maPhong")
	private Set<Phong> phongs = new HashSet<Phong>(0);

	public LoaiPhong() {
	}

	public LoaiPhong(String tenLoaiPhong, Set<Phong> phongs) {
		this.tenLoaiPhong = tenLoaiPhong;
		this.phongs = phongs;
	}

	public Integer getMaLoaiPhong() {
		return this.maLoaiPhong;
	}

	public void setMaLoaiPhong(Integer maLoaiPhong) {
		this.maLoaiPhong = maLoaiPhong;
	}

	public String getTenLoaiPhong() {
		return this.tenLoaiPhong;
	}

	public void setTenLoaiPhong(String tenLoaiPhong) {
		this.tenLoaiPhong = tenLoaiPhong;
	}

	public Set<Phong> getPhongs() {
		return this.phongs;
	}

	public void setPhongs(Set<Phong> phongs) {
		this.phongs = phongs;
	}

}
