package com.laptrinhtichhop.moigioinhatro.entities;
// Generated Dec 9, 2020, 8:44:57 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.Date;

/**
 * NguoiDiThue generated by hbm2java
 */
public class NguoiDiThue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String soCmnd;
	private Serializable hoTen;
	private String soDienThoai;
	private String email;
	private Date ngaySinh;
	private boolean gioiTinh;
	private Integer nganSach;
	private String tenDangNhap;

	public NguoiDiThue() {
	}

	public NguoiDiThue(String soCmnd, Serializable hoTen, String soDienThoai, Date ngaySinh, boolean gioiTinh,
			String tenDangNhap) {
		this.soCmnd = soCmnd;
		this.hoTen = hoTen;
		this.soDienThoai = soDienThoai;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.tenDangNhap = tenDangNhap;
	}

	public NguoiDiThue(String soCmnd, Serializable hoTen, String soDienThoai, String email, Date ngaySinh,
			boolean gioiTinh, Integer nganSach, String tenDangNhap) {
		this.soCmnd = soCmnd;
		this.hoTen = hoTen;
		this.soDienThoai = soDienThoai;
		this.email = email;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.nganSach = nganSach;
		this.tenDangNhap = tenDangNhap;
	}

	public String getSoCmnd() {
		return this.soCmnd;
	}

	public void setSoCmnd(String soCmnd) {
		this.soCmnd = soCmnd;
	}

	public Serializable getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(Serializable hoTen) {
		this.hoTen = hoTen;
	}

	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public boolean isGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	public Integer getNganSach() {
		return this.nganSach;
	}

	public void setNganSach(Integer nganSach) {
		this.nganSach = nganSach;
	}

	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

}
