package com.laptrinhtichhop.moigioinhatro.entities;
// Generated Dec 9, 2020, 8:44:57 PM by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * NguoiDung generated by hbm2java
 */
@Entity
@Table(name = "NGUOI_DUNG")
@XmlRootElement
public class NguoiDung implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ten_dang_nhap")
	private String tenDangNhap;

	@Column(name = "mat_khau")
	private String matKhau;

	@Transient
	@OneToMany(mappedBy = "maQuyenNguoiDung")
	private Set<QuyenNguoiDung> quyenNguoiDungs = new HashSet<QuyenNguoiDung>(0);

	public NguoiDung() {
	}

	public NguoiDung(String tenDangNhap, String matKhau) {
		this.tenDangNhap = tenDangNhap;
		this.matKhau = matKhau;
	}

	public NguoiDung(String tenDangNhap, String matKhau, Set<QuyenNguoiDung> quyenNguoiDungs) {
		this.tenDangNhap = tenDangNhap;
		this.matKhau = matKhau;
		this.quyenNguoiDungs = quyenNguoiDungs;
	}

	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	public Set<QuyenNguoiDung> getQuyenNguoiDungs() {
		return this.quyenNguoiDungs;
	}

	public void setQuyenNguoiDungs(Set<QuyenNguoiDung> quyenNguoiDungs) {
		this.quyenNguoiDungs = quyenNguoiDungs;
	}

}
