package com.laptrinhtichhop.moigioinhatro.entities;
// Generated Dec 9, 2020, 8:44:57 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.Date;

/**
 * PhieuGiuCho generated by hbm2java
 */
public class PhieuGiuCho implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer maPhieuGiuCho;
	private Date ngayDuKienDon;
	private int thoiHanThueDuKien;
	private Serializable loiNhan;
	private Date ngayLapPhieu;
	private Boolean trangThai;

	public PhieuGiuCho() {
	}

	public PhieuGiuCho(Date ngayDuKienDon, int thoiHanThueDuKien, Date ngayLapPhieu) {
		this.ngayDuKienDon = ngayDuKienDon;
		this.thoiHanThueDuKien = thoiHanThueDuKien;
		this.ngayLapPhieu = ngayLapPhieu;
	}

	public PhieuGiuCho(Date ngayDuKienDon, int thoiHanThueDuKien, Serializable loiNhan, Date ngayLapPhieu,
			Boolean trangThai) {
		this.ngayDuKienDon = ngayDuKienDon;
		this.thoiHanThueDuKien = thoiHanThueDuKien;
		this.loiNhan = loiNhan;
		this.ngayLapPhieu = ngayLapPhieu;
		this.trangThai = trangThai;
	}

	public Integer getMaPhieuGiuCho() {
		return this.maPhieuGiuCho;
	}

	public void setMaPhieuGiuCho(Integer maPhieuGiuCho) {
		this.maPhieuGiuCho = maPhieuGiuCho;
	}

	public Date getNgayDuKienDon() {
		return this.ngayDuKienDon;
	}

	public void setNgayDuKienDon(Date ngayDuKienDon) {
		this.ngayDuKienDon = ngayDuKienDon;
	}

	public int getThoiHanThueDuKien() {
		return this.thoiHanThueDuKien;
	}

	public void setThoiHanThueDuKien(int thoiHanThueDuKien) {
		this.thoiHanThueDuKien = thoiHanThueDuKien;
	}

	public Serializable getLoiNhan() {
		return this.loiNhan;
	}

	public void setLoiNhan(Serializable loiNhan) {
		this.loiNhan = loiNhan;
	}

	public Date getNgayLapPhieu() {
		return this.ngayLapPhieu;
	}

	public void setNgayLapPhieu(Date ngayLapPhieu) {
		this.ngayLapPhieu = ngayLapPhieu;
	}

	public Boolean getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Boolean trangThai) {
		this.trangThai = trangThai;
	}

}
