package com.laptrinhtichhop.moigioinhatro.entities;
// Generated Dec 9, 2020, 8:44:57 PM by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Phong generated by hbm2java
 */
@Entity
@Table(name = "PHONG")
@XmlRootElement
public class Phong implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ma_phong")
	private Integer maPhong;
	
	@JoinColumn(name = "ma_khu_vuc")
	@ManyToOne
	private KhuVuc khuVuc;
	
	@JoinColumn(name = "ma_loai_phong")
	@ManyToOne
	private LoaiPhong loaiPhong;

	@Column(name = "ten_phong")
	private String tenPhong;

	@Column(name = "dien_tich")
	private double dienTich;

	@Column(name = "suc_chua")
	private Integer sucChua;

	@Column(name = "dia_chi")
	private String diaChi;

	@Column(name = "mo_ta_them")
	private String moTaThem;
	
	@OneToMany(mappedBy = "maPhieuDang")
	private Set<PhieuDangPhong> phieuDangPhongs = new HashSet<PhieuDangPhong>(0);

	public Phong() {
	}

	public Phong(String tenPhong, double dienTich, String diaChi) {
		this.tenPhong = tenPhong;
		this.dienTich = dienTich;
		this.diaChi = diaChi;
	}

	public Phong(KhuVuc khuVuc, LoaiPhong loaiPhong, String tenPhong, double dienTich, Integer sucChua,
			String diaChi, String moTaThem, Set<PhieuDangPhong> phieuDangPhongs) {
		this.khuVuc = khuVuc;
		this.loaiPhong = loaiPhong;
		this.tenPhong = tenPhong;
		this.dienTich = dienTich;
		this.sucChua = sucChua;
		this.diaChi = diaChi;
		this.moTaThem = moTaThem;
		this.phieuDangPhongs = phieuDangPhongs;
	}

	public Integer getMaPhong() {
		return this.maPhong;
	}

	public void setMaPhong(Integer maPhong) {
		this.maPhong = maPhong;
	}

	public KhuVuc getKhuVuc() {
		return this.khuVuc;
	}

	public void setKhuVuc(KhuVuc khuVuc) {
		this.khuVuc = khuVuc;
	}

	public LoaiPhong getLoaiPhong() {
		return this.loaiPhong;
	}

	public void setLoaiPhong(LoaiPhong loaiPhong) {
		this.loaiPhong = loaiPhong;
	}

	public String getTenPhong() {
		return this.tenPhong;
	}

	public void setTenPhong(String tenPhong) {
		this.tenPhong = tenPhong;
	}

	public double getDienTich() {
		return this.dienTich;
	}

	public void setDienTich(double dienTich) {
		this.dienTich = dienTich;
	}

	public Integer getSucChua() {
		return this.sucChua;
	}

	public void setSucChua(Integer sucChua) {
		this.sucChua = sucChua;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getMoTaThem() {
		return this.moTaThem;
	}

	public void setMoTaThem(String moTaThem) {
		this.moTaThem = moTaThem;
	}

	public Set<PhieuDangPhong> getPhieuDangPhongs() {
		return this.phieuDangPhongs;
	}

	public void setPhieuDangPhongs(Set<PhieuDangPhong> phieuDangPhongs) {
		this.phieuDangPhongs = phieuDangPhongs;
	}

}
