package com.laptrinhtichhop.moigioinhatro.entities;
// Generated Dec 9, 2020, 8:44:57 PM by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * TienIch generated by hbm2java
 */
@Entity
@Table(name = "TIEN_ICH")
public class TienIch implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ma_tien_ich")
	private Integer maTienIch;

	@Column(name = "so_luong_may_lanh")
	private Integer soLuongMayLanh;

	@Column(name = "so_luong_wc_rieng")
	private Integer soLuongWcRieng;

	@Column(name = "co_cho_de_xe")
	private Boolean coChoDeXe;

	@Column(name = "so_luong_tu_lanh")
	private Integer soLuongTuLanh;

	@Column(name = "so_luong_ti_vi")
	private Integer soLuongTiVi;

	@Column(name = "so_luong_tu_quan_ao")
	private Integer soLuongTuQuanAo;

	@Column(name = "so_luong_may_nuoc_nong")
	private Integer soLuongMayNuocNong;

	@Column(name = "tien_ich_rieng")
	private String tienIchRieng;

	@OneToMany(mappedBy = "ma_phieu_dang")
	private Set<PhieuDangPhong> phieuDangPhongs = new HashSet<PhieuDangPhong>(0);
	

	public TienIch() {
	}

	public TienIch(Integer soLuongMayLanh, Integer soLuongWcRieng, Boolean coChoDeXe, Integer soLuongTuLanh,
			Integer soLuongTiVi, Integer soLuongTuQuanAo, Integer soLuongMayNuocNong, String tienIchRieng,
			Set<PhieuDangPhong> phieuDangPhongs) {
		this.soLuongMayLanh = soLuongMayLanh;
		this.soLuongWcRieng = soLuongWcRieng;
		this.coChoDeXe = coChoDeXe;
		this.soLuongTuLanh = soLuongTuLanh;
		this.soLuongTiVi = soLuongTiVi;
		this.soLuongTuQuanAo = soLuongTuQuanAo;
		this.soLuongMayNuocNong = soLuongMayNuocNong;
		this.tienIchRieng = tienIchRieng;
		this.phieuDangPhongs = phieuDangPhongs;
	}

	public Integer getMaTienIch() {
		return this.maTienIch;
	}

	public void setMaTienIch(Integer maTienIch) {
		this.maTienIch = maTienIch;
	}

	public Integer getSoLuongMayLanh() {
		return this.soLuongMayLanh;
	}

	public void setSoLuongMayLanh(Integer soLuongMayLanh) {
		this.soLuongMayLanh = soLuongMayLanh;
	}

	public Integer getSoLuongWcRieng() {
		return this.soLuongWcRieng;
	}

	public void setSoLuongWcRieng(Integer soLuongWcRieng) {
		this.soLuongWcRieng = soLuongWcRieng;
	}

	public Boolean getCoChoDeXe() {
		return this.coChoDeXe;
	}

	public void setCoChoDeXe(Boolean coChoDeXe) {
		this.coChoDeXe = coChoDeXe;
	}

	public Integer getSoLuongTuLanh() {
		return this.soLuongTuLanh;
	}

	public void setSoLuongTuLanh(Integer soLuongTuLanh) {
		this.soLuongTuLanh = soLuongTuLanh;
	}

	public Integer getSoLuongTiVi() {
		return this.soLuongTiVi;
	}

	public void setSoLuongTiVi(Integer soLuongTiVi) {
		this.soLuongTiVi = soLuongTiVi;
	}

	public Integer getSoLuongTuQuanAo() {
		return this.soLuongTuQuanAo;
	}

	public void setSoLuongTuQuanAo(Integer soLuongTuQuanAo) {
		this.soLuongTuQuanAo = soLuongTuQuanAo;
	}

	public Integer getSoLuongMayNuocNong() {
		return this.soLuongMayNuocNong;
	}

	public void setSoLuongMayNuocNong(Integer soLuongMayNuocNong) {
		this.soLuongMayNuocNong = soLuongMayNuocNong;
	}

	public String getTienIchRieng() {
		return this.tienIchRieng;
	}

	public void setTienIchRieng(String tienIchRieng) {
		this.tienIchRieng = tienIchRieng;
	}

	public Set<PhieuDangPhong> getPhieuDangPhongs() {
		return this.phieuDangPhongs;
	}

	public void setPhieuDangPhongs(Set<PhieuDangPhong> phieuDangPhongs) {
		this.phieuDangPhongs = phieuDangPhongs;
	}

}
